global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'analytics'
    static_configs:
      - targets: ['host.docker.internal:8900']
  - job_name: 'llm'
    static_configs:
      - targets: ['host.docker.internal:8200']
  - job_name: 'stt'
    static_configs:
      - targets: ['host.docker.internal:8700']
  - job_name: 'tts'
    static_configs:
      - targets: ['host.docker.internal:8800']
